--------------------------------------------------------
--  File created - Tuesday-November-11-2025   
--------------------------------------------------------

--------------------------------------------------------
--  CUSTOMER_ACTIVITY
--  Tracks login/logout activity of customers.
--------------------------------------------------------
CREATE TABLE CUSTOMER_ACTIVITY  
(
    ACTIVITY_ID      NUMBER(25,0), 
    LOGIN_TIME       DATE, 
    LOGOUT_TIME      DATE, 
    CUSTOMER_ID      NUMBER(25,0)
);

--------------------------------------------------------
--  CAR
--  Stores car details
--------------------------------------------------------
CREATE TABLE CAR   
(
    CAR_ID        NUMBER(25,0), 
    CAR_TYPE      VARCHAR2(50), 
    CAPACITY      NUMBER(2,0) DEFAULT 4, 
    RATE_PER_HR   NUMBER DEFAULT 10, 
    CAR_MODEL     VARCHAR2(50), 
    CAR_MAKE      VARCHAR2(50), 
    CAR_NUMBER    VARCHAR2(50)
);

--------------------------------------------------------
--  CARS_AT_PICKUP
--  Represents which cars are available at each pickup point.
--------------------------------------------------------
CREATE TABLE CARS_AT_PICKUP   
(
    CARS_AT_PICKUP_ID  NUMBER(25,0), 
    PICKUP_POINT_ID    NUMBER(25,0), 
    CAR_ID             NUMBER(25,0),
    STATUS             VARCHAR2(15)
);

--------------------------------------------------------
--  CUSTOMERS
-- Table storing customer identity details.
--------------------------------------------------------
CREATE TABLE CUSTOMERS   
(
    CUSTOMER_ID     NUMBER(25,0), 
    FIRST_NAME      VARCHAR2(50), 
    LAST_NAME       VARCHAR2(50), 
    DATE_OF_BIRTH   DATE,
    EMAIL_ID        VARCHAR2(50), 
    CONTACT         NUMBER(10,0), 
    LICENSE_NUMBER  VARCHAR2(50)
);

--------------------------------------------------------
--  CUSTOMER_ADDRESS
--------------------------------------------------------
CREATE TABLE CUSTOMER_ADDRESS   
(
    ADDRESS_ID      NUMBER(25,0), 
    CUSTOMER_ID     NUMBER(25,0),
    ADDRESS_TYPE    VARCHAR2(20) DEFAULT 'HOME',
    ADDRESS_LINE1   VARCHAR2(50), 
    ADDRESS_LINE2   VARCHAR2(50), 
    CITY            VARCHAR2(50), 
    STATE           VARCHAR2(50), 
    ZIP_CODE        VARCHAR2(10)
);

--------------------------------------------------------
--  FEEDBACK
--------------------------------------------------------
CREATE TABLE FEEDBACK   
(
    FEEDBACK_ID    NUMBER(25,0), 
    RATINGS        NUMBER(2,0), 
    COMMENTS       VARCHAR2(50), 
    FEEDBACK_DATE  DATE DEFAULT SYSDATE, 
    FEEDBACK_TYPE  VARCHAR2(10),
    TRANS_ID       NUMBER(25,0)
);

--------------------------------------------------------
--  PAYMENT 
--------------------------------------------------------
CREATE TABLE PAYMENT   
(
    PAYMENT_ID     NUMBER(25,0), 
    CARD_NUMBER    NUMBER(20,0),
    PAY_DATE       DATE DEFAULT SYSDATE, 
    CHARGE_TYPE    VARCHAR2(10),
    STATUS         VARCHAR2(15) DEFAULT 'IN PROCESS', 
    TRANS_ID       NUMBER(25,0), 
    DISCOUNT       NUMBER(25,0),
    AMOUNT         NUMBER(20,0)
);

--------------------------------------------------------
--  PICKUP_LOCATION
--  All pickup points available to customers.
--------------------------------------------------------
CREATE TABLE PICKUP_LOCATION   
(
    PICKUP_POINT_ID   NUMBER(25,0), 
    STATE             VARCHAR2(50), 
    CITY              VARCHAR2(50), 
    ZIP               VARCHAR2(10), 
    NAME              VARCHAR2(50)
);

--------------------------------------------------------
--  RIDE_TRANSACTION
--  Represents each ride taken by customers.
--------------------------------------------------------
CREATE TABLE RIDE_TRANSACTION   
(
    TRANS_ID            NUMBER(25,0), 
    CUSTOMER_ID         NUMBER(25,0), 
    CARS_AT_PICKUP_ID   NUMBER(25,0), 
    TRANSACTION_DATE    DATE DEFAULT SYSDATE, 
    START_TIME          TIMESTAMP(6), 
    END_TIME            TIMESTAMP(6), 
    CAR_ID              NUMBER(25,0), 
    DISTANCE            NUMBER(10,0) DEFAULT 0, 
    STATUS              VARCHAR2(20) DEFAULT 'IN PROCESS',
    DISCOUNT            NUMBER(25,0) DEFAULT 0
);

--------------------------------------------------------
--  SUPPORT
--  Customer support tickets.
--------------------------------------------------------
CREATE TABLE SUPPORT   
(
    SUPPORT_ID      NUMBER(25,0), 
    STATUS          VARCHAR2(15), 
    CUSTOMER_ID     NUMBER(25,0), 
    TRANS_ID        NUMBER(25,0),
    DESCRIPTION     VARCHAR2(50),
    SUPPORT_DATE    DATE
);

--------------------------------------------------------
--  VIOLATIONS
--------------------------------------------------------
CREATE TABLE VIOLATIONS   
(
    VIOLATION_ID   NUMBER(25,0), 
    DESCRIPTION    VARCHAR2(50)
);

--------------------------------------------------------
--  VIOLATIONS_RECORDS
--------------------------------------------------------
CREATE TABLE VIOLATIONS_RECORDS   
(
    RECORD_ID      NUMBER(25,0), 
    RECORD_DATE    DATE, 
    CUSTOMER_ID    NUMBER(25,0), 
    VIOLATION_ID   NUMBER(25,0)
);

--------------------------------------------------------
--  CONSTRAINTS
--  Adds PK, NOT NULL, UNIQUE, and CHECK constraints.
--------------------------------------------------------
-- SUPPORT
ALTER TABLE SUPPORT ADD CONSTRAINT SUPPORT_PK PRIMARY KEY (SUPPORT_ID);
ALTER TABLE SUPPORT MODIFY (TRANS_ID NOT NULL);
ALTER TABLE SUPPORT MODIFY (CUSTOMER_ID NOT NULL);
ALTER TABLE SUPPORT ADD CONSTRAINT STATUS_CHECK CHECK (STATUS IN ('IN PROGRESS','COMPLETED','PENDING'));

-- FEEDBACK
ALTER TABLE FEEDBACK ADD CONSTRAINT FEEDBACK_PK PRIMARY KEY (FEEDBACK_ID);
ALTER TABLE FEEDBACK MODIFY (TRANS_ID NOT NULL);

-- PICKUP_LOCATION
ALTER TABLE PICKUP_LOCATION ADD CONSTRAINT PICKUP_LOCATION_PK PRIMARY KEY (PICKUP_POINT_ID);
ALTER TABLE PICKUP_LOCATION MODIFY (STATE NOT NULL);
ALTER TABLE PICKUP_LOCATION MODIFY (CITY NOT NULL);
ALTER TABLE PICKUP_LOCATION MODIFY (ZIP NOT NULL);
ALTER TABLE PICKUP_LOCATION MODIFY (NAME NOT NULL);

-- CUSTOMER_ADDRESS
ALTER TABLE CUSTOMER_ADDRESS ADD CONSTRAINT CUSTOMER_ADDRESS_PK PRIMARY KEY (ADDRESS_ID);
ALTER TABLE CUSTOMER_ADDRESS MODIFY (CUSTOMER_ID NOT NULL);
ALTER TABLE CUSTOMER_ADDRESS MODIFY (ADDRESS_LINE1 NOT NULL);
ALTER TABLE CUSTOMER_ADDRESS MODIFY (CITY NOT NULL);
ALTER TABLE CUSTOMER_ADDRESS MODIFY (STATE NOT NULL);
ALTER TABLE CUSTOMER_ADDRESS MODIFY (ZIP_CODE NOT NULL);
ALTER TABLE CUSTOMER_ADDRESS ADD CONSTRAINT ADDRESS_TYPE_CHECK
    CHECK (ADDRESS_TYPE IN ('HOME','OFFICE','OTHER'));

-- PAYMENT
ALTER TABLE PAYMENT ADD CONSTRAINT PAYMENT_PK PRIMARY KEY (PAYMENT_ID);
ALTER TABLE PAYMENT MODIFY (CARD_NUMBER NOT NULL);
ALTER TABLE PAYMENT MODIFY (TRANS_ID NOT NULL);
ALTER TABLE PAYMENT ADD CONSTRAINT STATUS_CHECK1 CHECK (STATUS IN ('IN PROCESS','COMPLETED','PENDING'));

-- CAR
ALTER TABLE CAR ADD CONSTRAINT CAR_PK PRIMARY KEY (CAR_ID);
-- Car registration must be unique
ALTER TABLE CAR ADD CONSTRAINT CAR_NUMBER_UN UNIQUE (CAR_NUMBER); 
ALTER TABLE CAR MODIFY (CAR_TYPE NOT NULL);
ALTER TABLE CAR MODIFY (CAR_MODEL NOT NULL);
ALTER TABLE CAR MODIFY (CAR_MAKE NOT NULL);
ALTER TABLE CAR MODIFY (CAR_NUMBER NOT NULL);
ALTER TABLE CAR MODIFY (RATE_PER_HR NOT NULL);

-- VIOLATIONS_RECORDS
ALTER TABLE VIOLATIONS_RECORDS ADD CONSTRAINT VIOLATIONS_RECORDS_PK PRIMARY KEY (RECORD_ID);
ALTER TABLE VIOLATIONS_RECORDS MODIFY (VIOLATION_ID NOT NULL);
ALTER TABLE VIOLATIONS_RECORDS MODIFY (RECORD_DATE NOT NULL);
ALTER TABLE VIOLATIONS_RECORDS MODIFY (CUSTOMER_ID NOT NULL);

-- CUSTOMER_ACTIVITY
ALTER TABLE CUSTOMER_ACTIVITY ADD CONSTRAINT CUSTOMER_ACTIVITY_PK PRIMARY KEY (ACTIVITY_ID);

-- CUSTOMERS
ALTER TABLE CUSTOMERS ADD CONSTRAINT CUSTOMERS_PK PRIMARY KEY (CUSTOMER_ID);
ALTER TABLE CUSTOMERS MODIFY (FIRST_NAME NOT NULL);
ALTER TABLE CUSTOMERS MODIFY (EMAIL_ID NOT NULL);
ALTER TABLE CUSTOMERS MODIFY (CONTACT NOT NULL);
ALTER TABLE CUSTOMERS MODIFY (LICENSE_NUMBER NOT NULL);
-- Prevent duplicate emails
ALTER TABLE CUSTOMERS ADD CONSTRAINT CUSTOMERS_EMAIL_UN UNIQUE (EMAIL_ID); 
-- Prevent duplicate phone numbers 
ALTER TABLE CUSTOMERS ADD CONSTRAINT CUSTOMERS_CONTACT_UN UNIQUE (CONTACT);
-- Unique license  
ALTER TABLE CUSTOMERS ADD CONSTRAINT CUSTOMERS_LICENSE_UN UNIQUE (LICENSE_NUMBER);  

-- VIOLATIONS
ALTER TABLE VIOLATIONS ADD CONSTRAINT VIOLATIONS_PK PRIMARY KEY (VIOLATION_ID);
ALTER TABLE VIOLATIONS MODIFY (DESCRIPTION NOT NULL);

-- CARS_AT_PICKUP
ALTER TABLE CARS_AT_PICKUP ADD CONSTRAINT CARS_AT_PICKUP_PK PRIMARY KEY (CARS_AT_PICKUP_ID);
ALTER TABLE CARS_AT_PICKUP MODIFY (PICKUP_POINT_ID NOT NULL);

-- RIDE_TRANSACTION
ALTER TABLE RIDE_TRANSACTION ADD CONSTRAINT RIDE_TRANSACTION_PK PRIMARY KEY (TRANS_ID);
ALTER TABLE RIDE_TRANSACTION MODIFY (CARS_AT_PICKUP_ID NOT NULL);
ALTER TABLE RIDE_TRANSACTION MODIFY (END_TIME NOT NULL);
ALTER TABLE RIDE_TRANSACTION MODIFY (CUSTOMER_ID NOT NULL);
ALTER TABLE RIDE_TRANSACTION MODIFY (START_TIME NOT NULL);
ALTER TABLE RIDE_TRANSACTION MODIFY (STATUS NOT NULL);
ALTER TABLE RIDE_TRANSACTION ADD CONSTRAINT STATUS_CHECK2
    CHECK (STATUS IN ('IN PROCESS','COMPLETED','CANCELLED','UPDATED'));

--------------------------------------------------------
--  FOREIGN KEYS
--  Establish relationships between tables.
--------------------------------------------------------

ALTER TABLE CUSTOMER_ACTIVITY 
    ADD CONSTRAINT CUSTOMER_ACT_FK FOREIGN KEY (CUSTOMER_ID)
    REFERENCES CUSTOMERS(CUSTOMER_ID) ON DELETE CASCADE;      
    -- Delete activity if customer is deleted

ALTER TABLE CARS_AT_PICKUP 
    ADD CONSTRAINT CARS_PICKUP_POINT_FK FOREIGN KEY (PICKUP_POINT_ID)
    REFERENCES PICKUP_LOCATION(PICKUP_POINT_ID);

ALTER TABLE CARS_AT_PICKUP 
    ADD CONSTRAINT CARS_CAR_ID_FK FOREIGN KEY (CAR_ID)
    REFERENCES CAR(CAR_ID) ON DELETE SET NULL;  
    -- If car is removed, set car_id to NULL

ALTER TABLE CUSTOMER_ADDRESS 
    ADD CONSTRAINT CUST_ADDR_FK FOREIGN KEY (CUSTOMER_ID)
    REFERENCES CUSTOMERS(CUSTOMER_ID) ON DELETE CASCADE;  
    -- Delete addresses when customer is deleted

ALTER TABLE FEEDBACK 
    ADD CONSTRAINT FEEDBACK_TRANS_FK FOREIGN KEY (TRANS_ID)
    REFERENCES RIDE_TRANSACTION(TRANS_ID);

ALTER TABLE RIDE_TRANSACTION 
    ADD CONSTRAINT RTR_CARPICK_FK FOREIGN KEY (CARS_AT_PICKUP_ID)
    REFERENCES CARS_AT_PICKUP(CARS_AT_PICKUP_ID);

ALTER TABLE RIDE_TRANSACTION 
    ADD CONSTRAINT RTR_CUSTOMER_FK FOREIGN KEY (CUSTOMER_ID)
    REFERENCES CUSTOMERS(CUSTOMER_ID) ON DELETE SET NULL;

ALTER TABLE RIDE_TRANSACTION 
    ADD CONSTRAINT RTR_CAR_FK FOREIGN KEY (CAR_ID)
    REFERENCES CAR(CAR_ID) ON DELETE SET NULL;

ALTER TABLE SUPPORT 
    ADD CONSTRAINT SUPPORT_TRANS_FK FOREIGN KEY (TRANS_ID)
    REFERENCES RIDE_TRANSACTION(TRANS_ID);

ALTER TABLE SUPPORT 
    ADD CONSTRAINT SUPPORT_CUSTOMER_FK FOREIGN KEY (CUSTOMER_ID)
    REFERENCES CUSTOMERS(CUSTOMER_ID) ON DELETE CASCADE;

ALTER TABLE VIOLATIONS_RECORDS 
    ADD CONSTRAINT VR_VIOLATION_FK FOREIGN KEY (VIOLATION_ID)
    REFERENCES VIOLATIONS(VIOLATION_ID);

ALTER TABLE VIOLATIONS_RECORDS 
    ADD CONSTRAINT VR_CUSTOMER_FK FOREIGN KEY (CUSTOMER_ID)
    REFERENCES CUSTOMERS(CUSTOMER_ID) ON DELETE CASCADE;